export const TYPES = {
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    LOGOUT: "LOGOUT",
    GET_STUDENTS: "GET_STUDENTS",
    ADD_STUDENT: "ADD_STUDENT",
    EDIT_STUDENT: "EDIT_STUDENT",
    DROP_STUDENT: "DROP_STUDENT",
    VIEW_STUDENT: "VIEW_STUDENT",
    EDIT_GRADES: "EDIT_GRADES",
    GET_GRADES: "GET_GRADES",
    CLEAR_STATE: "CLEAR_STATE"
}